//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTemp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class huawei
    {
        public int id { get; set; }
        public string url { get; set; }
        public string name { get; set; }
        public string price { get; set; }
        public string ram { get; set; }
        public string rom { get; set; }
        public string backcam { get; set; }
        public string frontcam { get; set; }
        public string color { get; set; }
    }
}
